a=int(input('enter a number '))
b=int(input('enter second number '))
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)
#comment addition,subtraction,multiplication,float division(/),integer division(//),modulus operator remainder(%) (**-square)
